name: Anysnap Cloud Runner

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      node_id:
        description: 'Node ID for Worker (1 is Master)'
        required: true
        default: '1'

concurrency:
  group: anysnap-cloud-runner-${{ github.event.inputs.node_id || '1' }}
  cancel-in-progress: false

permissions:
  contents: read
  actions: write

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 360 

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Requirements
        run: pip install pyrogram tgcrypto docker psutil requests pymongo python-dotenv

      - name: Start Docker Daemon
        run: |
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Run Node
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          GH_PERSONAL_TOKEN: ${{ secrets.GH_PERSONAL_TOKEN }}
          GITHUB_REPO: ${{ secrets.REPO_NAME }}
          WORKFLOW_FILE: ${{ secrets.WORKFLOW_FILE }}
          OWNER_ID: ${{ secrets.OWNER_ID }}
          NODE_ID: ${{ github.event.inputs.node_id || '1' }}
          PYTHONUNBUFFERED: "1"
        run: |
          echo "======================================"
          echo "🚀 ANYSNAP CLOUD STARTING ON NODE: $NODE_ID"
          echo "======================================"
          python -u main.py
